#!/usr/bin/env python3
"""Features matrix hygiene check (recurring, every 2 weeks).

Three checks, per the Todoist recurring task:
  1. Competitor names resolve to the Benchmarks sheet
  2. Gap rows with no competitor named (unfounded gaps)
  3. Live rows unverified for more than 90 days (Live decay)

Sources:
  dashboard/data/features.json    (generated by xlsx-to-features-json.py)
  dashboard/data/benchmarks.json
  data/verified_live.json
"""
import json
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3].parent  # ~/Claude/ARC
DASH = Path(__file__).resolve().parents[1]
STALE_DAYS = 90


def load(p):
    with open(p) as fh:
        return json.load(fh)


def main(as_of=None):
    today = date.fromisoformat(as_of) if as_of else date.today()
    cutoff = today - timedelta(days=STALE_DAYS)

    features = load(DASH / "data" / "features.json")["features"]
    benchmarks = load(DASH / "data" / "benchmarks.json")["benchmarks"]
    verified = load(ROOT / "data" / "verified_live.json")

    known = {b["name"].strip().lower(): b["name"] for b in benchmarks}

    unknown_competitors = {}   # raw name -> [feature ids]
    unfounded_gaps = []        # Gap rows with no competitor
    stale_live = []            # Live rows verified > 90d ago
    never_verified = []        # Live rows never verified

    for f in features:
        fid, status = f["id"], f.get("status", "")
        comps = [c.strip() for c in f.get("competitors", []) if c.strip()]

        # Check 1 — competitor names resolve to Benchmarks
        for c in comps:
            if c.lower() not in known:
                unknown_competitors.setdefault(c, []).append(fid)

        # Check 2 — Gap with no competitor named
        if status == "Gap" and not comps:
            unfounded_gaps.append(f)

        # Check 3 — Live decay
        if status == "Live":
            rec = verified.get(fid)
            if not rec:
                never_verified.append(f)
            else:
                vd = date.fromisoformat(rec["verified_date"])
                if vd < cutoff:
                    stale_live.append((f, vd, (today - vd).days))

    live_total = sum(1 for f in features if f.get("status") == "Live")

    print(f"# Features Matrix Hygiene — {today.isoformat()}")
    print(f"Rows: {len(features)} | Live: {live_total} | "
          f"Benchmarks: {len(benchmarks)} | Verified records: {len(verified)}\n")

    print(f"## 1. Unresolved competitor names — {len(unknown_competitors)}")
    for name, ids in sorted(unknown_competitors.items(), key=lambda kv: -len(kv[1])):
        print(f"  {name!r} — {len(ids)} rows: {', '.join(sorted(ids)[:12])}"
              + (" …" if len(ids) > 12 else ""))
    if not unknown_competitors:
        print("  none — all competitor names resolve")

    print(f"\n## 2. Gap rows with no competitor named — {len(unfounded_gaps)}")
    by_journey = {}
    for f in unfounded_gaps:
        by_journey.setdefault(f.get("journey", "?"), []).append(f)
    for j, rows in sorted(by_journey.items(), key=lambda kv: -len(kv[1])):
        print(f"  {j} ({len(rows)}): "
              + ", ".join(f"{r['id']} {r['status']}" for r in rows))

    print(f"\n## 3. Live decay — {len(stale_live)} stale (>{STALE_DAYS}d), "
          f"{len(never_verified)} never verified")
    for f, vd, age in sorted(stale_live, key=lambda t: t[1]):
        print(f"  {f['id']} {f['name']} — last verified {vd} ({age}d ago)")
    if never_verified:
        nv_by_j = {}
        for f in never_verified:
            nv_by_j.setdefault(f.get("journey", "?"), []).append(f["id"])
        print("  Never verified, by journey:")
        for j, ids in sorted(nv_by_j.items(), key=lambda kv: -len(kv[1])):
            print(f"    {j} ({len(ids)}): {', '.join(sorted(ids))}")

    return {
        "unknown_competitors": unknown_competitors,
        "unfounded_gaps": unfounded_gaps,
        "stale_live": stale_live,
        "never_verified": never_verified,
    }


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
